name: Build and Deploy Azure Function App

on:
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: my-function-rg
  AZURE_FUNCTIONAPP_NAME: my-dotnet-functionapp
  AZURE_REGION: eastus
  AZURE_STORAGE_ACCOUNT: mystoragefunctionapp2025

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'  # Adjust based on your project

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      run: |
        az group create --name $AZURE_RESOURCE_GROUP --location $AZURE_REGION

    - name: Create Storage Account (if not exists)
      run: |
        az storage account create --name $AZURE_STORAGE_ACCOUNT --location $AZURE_REGION \
          --resource-group $AZURE_RESOURCE_GROUP --sku Standard_LRS || true

    - name: Create Function App (if not exists)
      run: |
        az functionapp create --resource-group $AZURE_RESOURCE_GROUP \
          --consumption-plan-location $AZURE_REGION \
          --runtime dotnet --functions-version 4 \
          --name $AZURE_FUNCTIONAPP_NAME \
          --storage-account $AZURE_STORAGE_ACCOUNT || true

    - name: Publish Azure Function App
      run: |
        dotnet publish -c Release -o publish_output
        func azure functionapp publish $AZURE_FUNCTIONAPP_NAME --dotnet
