name: Build and Deploy .NET Azure Function App

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: your-functionapp-name     # must be globally unique
  AZURE_RESOURCE_GROUP: your-resource-group-name
  AZURE_REGION: eastus                              # or westeurope, southeastasia, etc.
  AZURE_STORAGE_ACCOUNT: yourstorageacctname        # must be globally unique, lowercase only

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ✅ CI Triggered
      run: echo "GitHub Actions workflow has been triggered successfully."

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'  # or '6.x' if you're using .NET 9

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Azure resources if not exists
      run: |
        az group create --name $AZURE_RESOURCE_GROUP --location $AZURE_REGION
        az storage account create --name $AZURE_STORAGE_ACCOUNT --location $AZURE_REGION \
          --resource-group $AZURE_RESOURCE_GROUP --sku Standard_LRS || true
        az functionapp create --resource-group $AZURE_RESOURCE_GROUP \
          --consumption-plan-location $AZURE_REGION \
          --runtime dotnet --functions-version 4 \
          --name $AZURE_FUNCTIONAPP_NAME \
          --storage-account $AZURE_STORAGE_ACCOUNT || true

    - name: Build and package Function App
      run: |
        dotnet publish -c Release -o publish_output
        cd publish_output
        zip -r ../publish_output.zip .
        cd ..

    - name: Deploy to Azure Function App
      run: |
        az functionapp deployment source config-zip \
          --resource-group $AZURE_RESOURCE_GROUP \
          --name $AZURE_FUNCTIONAPP_NAME \
          --src publish_output.zip
